language: ruby
sudo: false

rvm:
  - 2.3.1
  - 2.3.0
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - rbx-2
  - jruby-9.0.5.0
  - jruby-head
  - ruby-head

before_install:
  - gem install bundler

bundler_args: --without test --jobs 3 --retry 3

before_script:
  - bundle update

